### PR TITLE
Fix Yahoo source invalid cookie / invalid crumb for v7 endpoint

### LINKED ISSUE #75: YahooError: Status 401: Invalid Cookie
Yesterday I started getting the following error when trying to use `bean-price`:
```
ERROR   : Error fetching EURUSD=X: Status 401: {'code': 'Unauthorized', 'description': 'Invalid Cookie'}
```

Command line:
```
bean-price --no-cache --clobber --inactive budget.beancount >> prices.beancount
```

When I remove `--no-cache`, the issue is almost gone, but not always.
I suppose it's related with rate limiting or other measures on Yahoo side.

### PR DESCRIPTION
**Pull request by xinluh**
Using approach similar to https://github.com/karlwancl/YahooFinanceApi/commit/14b6c587d94ebe551f11f44c6b954d64285b831c

Fixes #75

### CODE REVIEW

**Comment by iamkroot** [comment]
I added this, but get `Status 401: {'code': 'Unauthorized', 'description': 'Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback'}` error response.
Also, the `crumb` variable doesn't seem to be used in the current code.

**Comment by rizaon** [comment]
I can confirm that this fix works on my laptop. It will be great to have this merged.

**Comment by ileodo** [comment]
can we get this merged? @blais thanks

**Comment by blais** [comment]
You got it

**Pull request merged**
